@ECHO OFF

SET PATH=%cd%\dist\SqlComparator.jar

SET MSSQL_SERVER=MSSQL
SET MSSQL_CONN=jdbc:sqlserver://localhost:1433;databaseName=RBGCLIENT;trustServerCertificate=true;
SET MSSQL_USER=rbguser
SET MSSQL_PWD=rbgu53r

SET PGSQL_SERVER=PGSQL
SET PGSQL_CONN=jdbc:postgresql://localhost:5432/RBGCLIENT
SET PGSQL_USER=rbguser
SET PGSQL_PWD=rbgu53r

SET MARIA_SERVER=MARIA
SET MARIA_CONN=jdbc:mariadb://localhost:3306/RBGCLIENT1
SET MARIA_USER=rbguser
SET MARIA_PWD=rbgu53r

SET MAIN_DB_SERVER=%MARIA_SERVER%
SET MAIN_CONN=%MARIA_CONN%
SET MAIN_USER=%MARIA_USER%
SET MAIN_PWD=%MARIA_PWD%

SET SECOND_DB_SERVER=%MSSQL_SERVER%
SET SECOND_CONN=%MSSQL_CONN%
SET SECOND_USER=%MSSQL_USER%
SET SECOND_PWD=%MSSQL_PWD%

"%JAVA_HOME%\bin\java" -jar "%PATH%" %MAIN_DB_SERVER% %MAIN_CONN% %MAIN_USER% %MAIN_PWD% %SECOND_DB_SERVER% %SECOND_CONN% %SECOND_USER% %SECOND_PWD%

pause
